# Generated by Django 3.2.3 on 2021-05-27 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coursess', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['name'], 'verbose_name': 'Curso', 'verbose_name_plural': 'Cursos'},
        ),
    ]
