# Generated by Django 3.2.3 on 2021-06-03 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursess', '0004_enrollment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='status',
            field=models.IntegerField(blank=True, choices=[(0, 'Pendente'), (1, 'Aprovado'), (2, 'Cancelado')], default=1, verbose_name='Situação'),
        ),
    ]
