# Generated by Django 3.2.3 on 2021-06-03 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coursess', '0006_auto_20210603_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='coursess.course', verbose_name='Curso'),
        ),
    ]
